### ISSUE TITLE
[Visualization Hint] Bar chart: phần hướng dẫn trục X và Y bị sai

### ISSUE THREAD

**Issue by myvta** [datainsider-co/rocket-bi-web#17]
Đúng là: X- Revenue, Y- Year. Chú ý mũi tên.

![Screen Shot 2020-12-21 at 6 02 24 PM](https://user-images.githubusercontent.com/44155302/102770511-db763c80-43b6-11eb-8b04-751e29528671.png)

**Comment by tvc12** [comment]
+ [ ] Bubble chart bị thiếu phần chỉ vào legend #16 
+ [ ] Scatter sai mũi tên chỉ trục x và y #15
+ [ ] Histogram bị sai #40
